export const zoneList = [
  { zone: '16S' },
  { zone: '17S' },
  { zone: '18S' },
  { zone: '19S' },
  { zone: '20S' },
  { zone: '21S' },
  { zone: '22S' },
  { zone: '23S' },
  { zone: '24S' },
  { zone: '25S' },
  { zone: '16N' },
  { zone: '17N' },
  { zone: '18N' },
  { zone: '19N' },
  { zone: '20N' },
  { zone: '21N' },
  { zone: '22N' },
  { zone: '23N' },
  { zone: '24N' },
  { zone: '25N' },
]
